### PR TITLE
Issue 1011 (update to angular 6)

### PR DESCRIPTION
**Pull request by j987987**
Instructions:

Local test:
- `npm i`
- `npm run serve:local:dev:uac`
- Confirm everything works as expected

Docker test (node-sass is causing problems atm)
- Stop stack, `docker rmi unfetter-ui`
- Restart stack
- Confirm everything works as expected

### CODE REVIEW

**Comment by mushinlogit** [comment]
threat dashboard default data does not show charts and has a console error

screen shot 2018-06-19 at 5 11 09 pm

**Comment by mushinlogit** [comment]
running `npm start` assessment beta edit has page load issues?  
clicking a button populates the page... so maybe something happened with change detection?  See screen shot
screen shot 2018-06-20 at 10 50 48 am

**Comment by mushinlogit** [comment]
running npm start assessment edit has page load issues?
clicking a button populates the page... so maybe something happened with change detection? See screen shot

screen shot 2018-06-20 at 10 50 34 am

**Comment by j987987** [comment]
fixes unfetter-discover/unfetter#1011

**Pull request merged**
