### PR TITLE
Issue 692/delete threatdashboard

### PR DESCRIPTION
**Pull request by mushinlogit**
supports unfetter-discover/unfetter#692 

This PR requires unfetter-discover/unfetter-store#84

## To Test
* Pull this PR
* Navigate to the threat report or assessments icon in the app header
* verify the create or last modified object is routed to
* if it is a create page, click cancel verify the page routes back to previous
* `npm run lint && npm run build:dev && npm test && npm run coverage`

### CODE REVIEW

**Comment by mushinlogit** [comment]
can verify delete functionality in another PR when create workproduct #221 is resolved

**Comment by j987987** [comment]
`unfetter-ui/src/app/assess/create/create.component.spec.ts` fails

**Comment by mushinlogit** [comment]
rebased and fixed test, ready for review

**Comment by mpmmasterpeace** [comment]
Tests pass functionality works as described.

Some issues:

- How do you get to a list of assessments or work products if you have not edited one? I get to the create screen in this case and cancelling causes me to go back one page.
- Deleting the current assessment or work product seems a bit hit or miss as to what happens. What should happen?
- The edit capability from the side panel header seems a bit wonky. Does not work for work products for the vertical "more" menu. Only get the title for editing an assessment.

Of course these can be handled in other Issues. Let me know what you want to do about this PR @mushinlogit

**Comment by mushinlogit** [comment]
@mpmmasterpeace 
* viewing others vs your own assessments has not fully been thought through.  At the moment in UAC mode, it is not encouraged for you to view others assessments
* delete current is handled better, see last commit
* when editing an assessment is not implemented see unfetter-discover/unfetter/issues/693

**Comment by mpmmasterpeace** [comment]
Looks good. Passing tests.

**Pull request merged**
