### PR TITLE
Issue 688/assess wizard nav

### PR DESCRIPTION
**Pull request by mushinlogit**
supports unfetter-discover/unfetter#688

better navigation in wizard.

## To Test 
* pull this branch
* visit, https://localhost/#/assess/create
* navigate the wizard, notice the summary link to jump directly to a save page
* navigate back and forth
* save, notice route to summary results page
* `npm run lint && npm run build:prod && npm run test && npm run coverage`, verify

### CODE REVIEW

**Comment by sbertrandmitre** [comment]
My only comment on this would be questioning the need for a sub "Summary" link, though I can understand if it would be preferred to keep some consistency with the other category links (i.e. Indicators, Mitigations, Sensors).  If it is possible to just make the Summary category lead directly to the "Save" page, it would provide less redundancy.

**Comment by mpmmasterpeace** [comment]
@sbertrandmitre I'm not following your comment. Summary is a view of information about a completed assessment; Full Results will be a different view of the same assessment. An assessment can include one or more of Indicator, Mitigation, and Sensor categories.

Let me know if that doesn't clarify the intent of the Summary view. I'd be happy to discuss further.

**Comment by sbertrandmitre** [comment]
screen shot 2018-01-31 at 11 50 59 am
Sorry - I was meaning to convey that the sub-link for Summary probably isn't needed.  The main Summary link would suffice.

**Comment by mpmmasterpeace** [comment]
Ah, that makes sense. I had the same thought clicking through. I thought clicking on SUMMARY should be enough to get me to the Summary page, but I can see the parity with categories argument as well.

**Pull request merged**
