### PR TITLE
Issue 642/edit report dialog

### PR DESCRIPTION
**Pull request by webiator**
Should now be able to
- add, modify and save-as reports in a work product;
- save the product; and,
- modify the product.

Note that this PR does not close the referenced ticket. Still need to add the "import report" feature.

### CODE REVIEW

**Comment by mpmmasterpeace** [comment]
I have reviewed and note the following issues:

- Could not delete a report from a Work Product prior to save (after save, modifying the work product allowed deleting the report); this also caused 502 errors from any call to api/reports after that time. Required restart of webserver to correct.
- Minor deviations from wireframe mock-ups; recommend fixing overall indentation of the Modify Work Product page to match wireframe
- May be outside the scope of this ticket, but saving a work product and then viewing it from the sidebar Edit menu does not dire
- Some console.logs in code report-editor.component.ts:197 for example.
- Would recommend some additional unit testing as coverage is low

If you want to write these issues up (or would like me to) I am willing to merge this in as a WIP. Or if you want to fix them here, that's fine too. Let me know.

**Comment by webiator** [comment]
Let me come in tomorrow and take a look; I thought I was able to do the things you point out (deleting report prior to save, editing from the sidebar, wireframe).

**Comment by webiator** [comment]
Delete report fixed. After discussion, created new feature #700.

Console log message cleaned up.

Added unit tests.

**Comment by mpmmasterpeace** [comment]
Tests pass; functionality is good.
Recommend fixing these issues in another issue/branch:

- save as with same name as existing report can cause deletion of both reports
- fix this line in threat-report-editor.component.ts: "public readonly dateFormat = this.dateFormat;" 
- remove console.log "fetch complete"

**Pull request merged**
