### PR TITLE
Issue 1085/edit baseline

### LINKED ISSUE #1085: Baselines:  Support editing of existing baselines through sidebar and master list
For existing baselines, code is needed to read the ID of the baseline passed into the wizard, and to populate the baseline store with that baseline's objects.

### PR DESCRIPTION
**Pull request by shawnbertrand**
Requires unfetter-discover/unfetter@1127
Fixes unfetter-discover/unfetter#1085

Baselines can now be edited, though this PR has code which treats the `category` attribute of a `Capability` as an ID instead of category name.  Sample capability data in config/examples/unfetter-stix/assessments3/capabilities.stix.json in the unfetter repo must be updated, and so you'll want to pull https://github.com/unfetter-discover/unfetter/pull/1127.  The `category` attribute will be renamed as well but in a subsequent PR.

There is a bug in how new baselines are saved, in that assessed_object entries for each object assessment are empty.  This results in an empty weighting panel for each capability.  This will be fixed in a subsequent PR as well, as it is not related to loading of a baseline for edit purposes.

## To test:
1. Pull this feature
2. Drop the stix DB
3. Restart the stack
4. Click the down arrow in the sidebar and select `Edit`
5. Verify that the capability group(s) and capability(ies) are listed correctly in the wizard.
6. Exit the wizard and click the down arrow in the sidebar to display the master list of baselines
7. Click the edit button for one of the other baselines
8. Repeat steps 3 through 5

### CODE REVIEW

**Review by mushinlogit — DISMISSED** [review]
error in console when trying to edit...

**Comment by sbertrandmitre** [comment]
Please note:  unfetter-discover/unfetter#1127 is required to verify this.  Otherwise, you'll get errors attempting to edit existing and new baselines.

**Comment by webiator** [comment]
I don't know what error @mushinlogit was getting, but I am working #1127 as well, and am seeing this error _when I click on a capability_ (which may not be the scope of this PR, please advise if it is not):
```
ERROR TypeError: Cannot read property 'category' of undefined
    at eval (wizard.component.ts:344)
    at Array.find (<anonymous>)
    at WizardComponent.navigationClicked (wizard.component.ts:344)
    at Object.eval [as handleEvent] (WizardComponent.html:22)
    ...
```

**Comment by sbertrandmitre** [comment]
It would seem to me that clicking a capability while in the wizard is not related to initiating an edit of an existing baseline.  Chances are, that error would occur with new or editing baselines.

**Review by ghost — APPROVED** [review]
Error with clicking capability not related to this PR. All checks pass.

**Pull request merged**
